{{- if .Values.ingress.rewriteTargets }}
{{- range $i, $target := .Values.ingress.rewriteTargets }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" $ }}-replacepathregex-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  replacePathRegex:
    regex: {{ $target.regex }}
    replacement: {{ $target.replacement }}
---
{{- end }}
{{- end }}
{{- if .Values.ingress.rewriteBody }}
{{- range $i, $target := .Values.ingress.rewriteBody }}
# Replace body with regex
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" $ }}-replacebodyregex-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  plugin:
    rewriteBody:
      rewrites:
      - regex: {{ $target.regex | quote }}
        replacement: {{ $target.replacement | quote }}
      logLevel: {{ default $target.logLevel 0 }}
      {{- if $target.monitoring }}
      monitoring:
        {{- if $target.methods }}
        methods:
          {{- range $index, $element := $target.methods }}
          - {{ $element | quote }}
          {{- end }}
        {{- end }}
        {{- if $target.types }}
        types:
          {{- range $index, $element := $target.types }}
          - {{ $element | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}