{{- if and (eq .Values.postgresql.enabled false) (eq .Values.storage.enabled true) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.chartname" . }}-postgres-volume
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgresql.primary.persistence.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.postgresql.primary.persistence.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.chartname" . }}-postgres-claim
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size }}
{{- end }}    